name: Build Ramaki Tunnel
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zlib1g-dev libssl-dev libffi-dev autoconf automake libtool
        pip install --upgrade pip
        pip install buildozer cython kivy requests pillow
    - name: Build with Buildozer
      run: |
        buildozer android debug
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Ramaki_Tunnel_APK
        path: bin/*.apk
